FROM python:3.13-slim

RUN apt-get update && \
    apt-get install -y gcc
RUN pip install poetry

WORKDIR /app
COPY pyproject.toml poetry.lock /app/

RUN poetry install --no-interaction --no-ansi --no-root
ENV POETRY_VIRTUALENVS_CREATE=false

COPY ./src /app/src

