services:
  base:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.base
    image: custom-base

  postgres:
    image: postgres:17.0
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    profiles: ["", "dev"]

  bot:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.bot
    container_name: bot
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - base
      - postgres
      - fastapi
    networks:
      - app_network
    restart: unless-stopped
    profiles: [""]

  fastapi:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.fastapi
    container_name: fastapi
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - postgres
      - base
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app_network
    profiles: [""]

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge