# Базовый образ для вашего приложения (например, Python)
FROM python:3.13-slim

# Устанавливаем зависимости для Alembic
RUN pip install alembic sqlalchemy asyncpg pydantic-settings greenlet

# Копируем ваш проект в контейнер
WORKDIR /app
COPY . .

# Команда, которая будет выполнена по умолчанию (необязательно)
CMD ["alembic", "upgrade", "head"]
