FROM python:3.13-slim

RUN apt-get update && \
    apt-get install -y gcc
RUN pip install poetry

WORKDIR /app
COPY pyproject.toml poetry.lock /app/

ENV POETRY_VIRTUALENVS_CREATE=false
RUN poetry install --no-interaction --no-ansi --no-root

COPY src /app/src
COPY alembic.ini /app/alembic.ini